### ISSUE TITLE
DON'T FORGET 

### ISSUE THREAD

**Issue by mrfltvs** [JSMongere/Sort-of-CODE#2]
public:
        Blockchain() {
            difficulty = 3;
            chain.push_back(createGenesisBlock());
        }

**Comment by mrfltvs** [comment]
public:
        Blockchain() {
            difficulty = 3;
            chain.push_back(createGenesisBlock());
        }

**Comment by JSMongere** [comment]
Ok

**Comment by mrfltvs** [comment]
Block createGenesisBlock() {
            std::string data = "Genesis Block";
            std::string previousHash = "0";
            return Block(data, previousHash);
        }
